### ISSUE TITLE
Problem install plugin

### ISSUE THREAD

**Issue by mrd3v1lz** [bjoerns1983/jellyfin-plugin-telegramnotification#2]
Hi

I downloaded the file and put it via ftp in the var/lib/jellyfin/plugins/
I also revived the server, but the plugin does not come out inside the plugins section of the jellyfin platform

what did I do wrong?

**Comment by bjoerns1983** [comment]
Maybe permissions? Dont know i dont actively use Jellyfin, i have only ported that plugin on request and tested it using Windows. Maybe the guys over at the Jellyfin Forum have a clue.

**Comment by mrd3v1lz** [comment]
what permeate do I have to put?

I'm using linux

**Comment by bjoerns1983** [comment]
In worst case try it with 777, like i said i have not tested it.

**Comment by mrd3v1lz** [comment]
nothing doesn't come out yet

**Comment by mrd3v1lz** [comment]
now I was reading on the forum, do you have to fill out first?

how do I do it?

**Comment by bjoerns1983** [comment]
I dont understand what you mean.

**Comment by mrd3v1lz** [comment]
Install the Plugin by downloading the DLL (or build it yourself using VS2019) and putting it into your Jellyfin Plugin folder

what do you mean here?

**Comment by bjoerns1983** [comment]
That you should download or build the DLL and that you put it in the Plugin folder of Jellyfin.
If you dont know how to do that please ask on the Jellyfin Forum. I doubt that your problem is specific to this plugin.

**Comment by mrd3v1lz** [comment]
ok thanks
