### ISSUE TITLE
Error sending the test notification

### ISSUE THREAD

**Issue by araynard** [bjoerns1983/jellyfin-plugin-telegramnotification#3]
I run Jellyfin 10.5.2 in docker on a raspberry pi 4.
I set up the same bot I got working for other services (Sonnar, Radarr).
After clinking "Test Notification" I have a dialog popping up:

> There was an error sending the test notification. Please check your notification settings and try again.

I found this related messages in the log:
`[2020-04-05 20:25:43.404 +02:00] [ERR] [47] Emby.Server.Implementations.HttpServer.HttpListenerHost: Could not find handler for "/jellyfin/Notification/Telegram/Test/84c2a958c61a498baa2b5b23c2f7f77b"
[2020-04-05 20:25:43.405 +02:00] [ERR] [47] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "Unable to find the specified file."`

**Comment by bjoerns1983** [comment]
This is a known issue because Jellyfin removed some Handlers which were integrated in Emby. Test Notification fails but normale Messages will be send.
