### ISSUE TITLE
Sending notifications that it shouldn't be

### ISSUE THREAD

**Issue by m0ngr31** [bjoerns1983/jellyfin-plugin-telegramnotification#5]
I just installed the plugin the other day, and it works great, except for 2 small things:

- It always notifies me when something is imported into the library event though I have that notification disabled.
- It always notifies me when a user starts playback when I told it not to for that specific user.

**Comment by bjoerns1983** [comment]
Thats no issue of the plugin. It only forwards everything Jellyfin sends it as notification. The plugin itself does not select what to send.

**Comment by m0ngr31** [comment]
Good to know. I'll bring it up with the Jellyfin folks!
